name: Build Android APK

on:
  push:
    tags:
      - 'v1.1.0'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests (Optional)
        if: startsWith(github.ref, 'refs/tags/v')
        run: flutter test --machine | tee result.json

      - name: Decode and save Android keystore
        run: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/newspaper_app.jks
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      - name: Configure Gradle with keystore info
        run: |
          sed -i 's|signingConfig = signingConfigs.getByName("release")|signingConfig = signingConfigs.create("release")|' android/app/build.gradle.kts
          sed -i 's|keyAlias = "newspaper_app"|keyAlias = System.getenv("ANDROID_KEY_ALIAS")|' android/app/build.gradle.kts
          sed -i 's|keyPassword = "123456"|keyPassword = System.getenv("ANDROID_KEY_PASSWORD")|' android/app/build.gradle.kts
          sed -i 's|storePassword = "123456"|storePassword = System.getenv("ANDROID_STORE_PASSWORD")|' android/app/build.gradle.kts
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
