name: Build Android APK

on:
  push:
    tags:
      - 'v1.2.0'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests (Optional)
        if: startsWith(github.ref, 'refs/tags/v')
        run: flutter test --machine | tee result.json

      - name: Decode Android keystore
        run: echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/newspaper_app.jks
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      - name: Configure keystore in Gradle
        run: |
          sed -i 's|keyAlias = ".*"|keyAlias = System.getenv("ANDROID_KEY_ALIAS")|' android/key.properties
          sed -i 's|keyPassword = ".*"|keyPassword = System.getenv("ANDROID_KEY_PASSWORD")|' android/key.properties
          sed -i 's|storePassword = ".*"|storePassword = System.getenv("ANDROID_STORE_PASSWORD")|' android/key.properties
          sed -i 's|storeFile = file(".*")|storeFile = file("newspaper_app.jks")|' android/key.properties
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
