name: Build iOS IPA

on:
  push:
    tags:
      - 'v1.0.2'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Xcode Command Line Tools
        run: |
          if ! xcode-select --print-path &>/dev/null; then
            sudo xcode-select --install
          else
            echo "Xcode Command Line Tools are already installed."
          fi

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests (Optional)
        run: flutter test --machine | tee result.json
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

      - name: Build iOS Debug IPA
        run: |
          flutter clean
          flutter build ipa --no-codesign

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa